from tkinter import *
window= Tk()
window.resizable(0,0)
a= StringVar()
def clear():
    a.set("")
def setbtn(value):
    a.set(a.get()+value)
def answer():
    ans=eval(a.get())
    a.set(ans)
window.title("Calculator using Python")
window.geometry("320x280")
entry= Entry(window,font=("",20),justify="right",textvariable=a)
entry.grid(row=0,column=0,columnspan=3,padx=5,pady=5)
b1=Button(window,text="clear",width=10,command=clear)
b1.grid(row=1,column=0,padx=5,pady=5)
b2=Button(window,text="0",width=10,command=lambda:setbtn("0"))
b2.grid(row=1,column=1,padx=5,pady=5)
b3=Button(window,text=".",width=10,command=lambda:setbtn("."))
b3.grid(row=1,column=2,padx=5,pady=5)
nine=Button(window,text="9",width=10,command=lambda:setbtn("9"))
nine.grid(row=2,column=0,padx=5,pady=5)
eight=Button(window,text="8",width=10,command=lambda:setbtn("8"))
eight.grid(row=2,column=1,padx=5,pady=5)
seven=Button(window,text="7",width=10,command=lambda:setbtn("7"))
seven.grid(row=2,column=2,padx=5,pady=5)
six=Button(window,text="6",width=10,command=lambda:setbtn("6"))
six.grid(row=3,column=0,padx=5,pady=5)
five=Button(window,text="5",width=10,command=lambda:setbtn("5"))
five.grid(row=3,column=1,padx=5,pady=5)
four=Button(window,text="4",width=10,command=lambda:setbtn("4"))
four.grid(row=3,column=2,padx=5,pady=5)
three=Button(window,text="3",width=10,command=lambda:setbtn("3"))
three.grid(row=4,column=0,padx=5,pady=5)
two=Button(window,text="2",width=10,command=lambda:setbtn("2"))
two.grid(row=4,column=1,padx=5,pady=5)
one=Button(window,text="1",width=10,command=lambda:setbtn("1"))
one.grid(row=4,column=2,padx=5,pady=5)
div=Button(window,text="/",width=10,command=lambda:setbtn("/"))
div.grid(row=5,column=0,padx=5,pady=5)
mul=Button(window,text="*",width=10,command=lambda:setbtn("*"))
mul.grid(row=5,column=1,padx=5,pady=5)
add=Button(window,text="+",width=10,command=lambda:setbtn("+"))
add.grid(row=5,column=2,padx=5,pady=5)
sub=Button(window,text="-",width=10,command=lambda:setbtn("-"))
sub.grid(row=6,column=0,padx=5,pady=5)
mod=Button(window,text="%",width=10,command=lambda:setbtn("%"))
mod.grid(row=6,column=1,padx=5,pady=5)
equal=Button(window,text="=",width=10,command=answer)
equal.grid(row=6,column=2,padx=5,pady=5)
window.mainloop()